"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useState } from "react";

import type { AdminDocument, DocumentCategory } from "@/features/documents/domain/document";
import { createPlainRichText, hasRichTextContent, type SafeRichTextDocument } from "@/features/documents/domain/rich-text";
import { RichTextRenderer } from "@/features/documents/components/rich-text-renderer";
import { normalizeImageForUpload } from "@/features/media/client/normalize-image-for-upload";
import { DocumentRichTextEditor } from "./document-rich-text-editor";
import styles from "./admin-document-editor.module.css";

const empty = createPlainRichText("");
export function AdminDocumentEditor({ document }: { document: AdminDocument | null }) {
  const router = useRouter(); const [slug, setSlug] = useState(document?.slug ?? ""); const [category, setCategory] = useState<DocumentCategory>((document?.category as DocumentCategory) ?? "guide");
  const [titleTh, setTitleTh] = useState(document?.title.th ?? ""); const [titleEn, setTitleEn] = useState(document?.title.en ?? ""); const [summaryTh, setSummaryTh] = useState(document?.summary.th ?? ""); const [summaryEn, setSummaryEn] = useState(document?.summary.en ?? "");
  const [contentTh, setContentTh] = useState<SafeRichTextDocument>(document?.content.th ?? empty); const [contentEn, setContentEn] = useState<SafeRichTextDocument>(document?.content.en ?? empty); const [tags, setTags] = useState(document?.tags.map((tag) => `${tag.th}|${tag.en}`).join(", ") ?? "");
  const [pinned, setPinned] = useState(document?.pinned ?? false); const [published, setPublished] = useState(document?.published ?? false); const [displayOrder, setDisplayOrder] = useState(document?.displayOrder ?? 0); const [coverMediaId, setCoverMediaId] = useState<string | null>(document?.coverMediaId ?? null); const [coverSrc, setCoverSrc] = useState(document?.coverMedia?.cardSrc ?? ""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function upload(file: File) { setBusy(true); setError(""); try { const normalized = await normalizeImageForUpload(file); const form = new FormData(); form.set("file", normalized.file); form.set("altTh", titleTh); form.set("altEn", titleEn); const response = await fetch("/api/admin/documents/media", { body: form, method: "POST" }); const body = await response.json() as { error?: string; mediaId?: string; src?: string }; if (!response.ok || !body.mediaId || !body.src) throw new Error(body.error ?? "อัปโหลดรูปปกไม่สำเร็จ"); setCoverMediaId(body.mediaId); setCoverSrc(body.src); } catch (cause) { setError(cause instanceof Error ? cause.message : "อัปโหลดรูปปกไม่สำเร็จ"); } finally { setBusy(false); } }
  async function save() { setError(""); if (!slug.trim()) { setError("กรุณากรอก Slug"); return; } if (published && (!titleTh.trim() || !titleEn.trim() || !summaryTh.trim() || !summaryEn.trim() || !hasRichTextContent(contentTh) || !hasRichTextContent(contentEn))) { setError("เอกสารที่จะเผยแพร่ต้องมีข้อมูลไทยและอังกฤษครบ"); return; } setBusy(true); try { const localizedTags = tags.split(",").map((tag) => tag.trim()).filter(Boolean).map((tag) => { const [th, en = th] = tag.split("|").map((value) => value.trim()); return { en, th }; }); const response = await fetch(document ? `/api/admin/documents/${document.id}` : "/api/admin/documents", { body: JSON.stringify({ category, content: { en: contentEn, th: contentTh }, coverMediaId, displayOrder, pinned, published, slug: slug.trim(), summary: { en: summaryEn, th: summaryTh }, tags: localizedTags, title: { en: titleEn, th: titleTh } }), headers: { "content-type": "application/json" }, method: document ? "PATCH" : "POST" }); const body = await response.json().catch(() => ({})) as { documentId?: string; error?: string }; if (!response.ok) throw new Error(body.error ?? "บันทึกไม่สำเร็จ"); router.push("/admin/documents"); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "บันทึกไม่สำเร็จ"); } finally { setBusy(false); } }
  return <section className={styles.page}><header><div><p>DOCUMENT CMS</p><h1>{document ? "แก้ไขเอกสาร" : "สร้างเอกสาร"}</h1></div><div><button disabled={busy} onClick={save} type="button">บันทึกเอกสาร</button></div></header>{error ? <p className={styles.error} role="alert">{error}</p> : null}<div className={styles.layout}><div className={styles.form}>
    <section><h2>ข้อมูลเอกสาร</h2><div className={styles.two}><label>Slug<input aria-label="Slug" onChange={(event) => setSlug(event.target.value)} value={slug} /></label><label>หมวดหมู่<select onChange={(event) => setCategory(event.target.value as DocumentCategory)} value={category}><option value="terms">ข้อตกลง</option><option value="guide">คู่มือ</option><option value="privacy">ความเป็นส่วนตัว</option></select></label></div><div className={styles.two}><label>ชื่อภาษาไทย<input aria-label="ชื่อภาษาไทย" onChange={(event) => setTitleTh(event.target.value)} value={titleTh} /></label><label>ชื่อภาษาอังกฤษ<input aria-label="ชื่อภาษาอังกฤษ" onChange={(event) => setTitleEn(event.target.value)} value={titleEn} /></label></div><div className={styles.two}><label>สรุปภาษาไทย<textarea aria-label="สรุปภาษาไทย" onChange={(event) => setSummaryTh(event.target.value)} value={summaryTh} /></label><label>สรุปภาษาอังกฤษ<textarea aria-label="สรุปภาษาอังกฤษ" onChange={(event) => setSummaryEn(event.target.value)} value={summaryEn} /></label></div><label>แท็ก (ไทย|English คั่นด้วย comma)<input onChange={(event) => setTags(event.target.value)} value={tags} /></label></section>
    <section><DocumentRichTextEditor label="เนื้อหาภาษาไทย" onChange={setContentTh} value={contentTh} /><DocumentRichTextEditor label="English content" onChange={setContentEn} value={contentEn} /></section></div><aside><section><h2>การเผยแพร่</h2><label className={styles.check}><input aria-label="เผยแพร่" checked={published} onChange={(event) => setPublished(event.target.checked)} type="checkbox" />เผยแพร่</label><label className={styles.check}><input checked={pinned} onChange={(event) => setPinned(event.target.checked)} type="checkbox" />ปักหมุด</label><label>ลำดับ<input min="0" onChange={(event) => setDisplayOrder(Number(event.target.value))} type="number" value={displayOrder} /></label></section><section><h2>รูปปก (ไม่บังคับ)</h2>{coverSrc ? <Image alt="ตัวอย่างรูปปก" height={140} src={coverSrc} width={240} /> : null}<input accept="image/png,image/jpeg,image/webp" aria-label="อัปโหลดรูปปก" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); }} type="file" /></section><section><h2>ตัวอย่างไทย</h2><h3>{titleTh || "ชื่อเอกสาร"}</h3><p>{summaryTh}</p><RichTextRenderer document={contentTh} /></section></aside></div></section>;
}
