"use client";

import { Archive, FilePlus2, FileText, Pencil, RotateCcw, Search } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";

import type { AdminDocument } from "@/features/documents/domain/document";
import styles from "./admin-documents-page.module.css";

const categoryLabels = { guide: "คู่มือ", privacy: "ความเป็นส่วนตัว", terms: "ข้อตกลง" } as const;
export function AdminDocumentsPage({ documents }: { documents: AdminDocument[] }) {
  const router = useRouter(); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [busyId, setBusyId] = useState<string | null>(null); const [error, setError] = useState("");
  const visible = useMemo(() => { const term = query.trim().toLocaleLowerCase("th"); return documents.filter((document) => { if (status === "published" && (!document.published || document.archivedAt)) return false; if (status === "draft" && (document.published || document.archivedAt)) return false; if (status === "archived" && !document.archivedAt) return false; return !term || [document.title.th, document.title.en, document.slug, categoryLabels[document.category as keyof typeof categoryLabels] ?? document.category].join(" ").toLocaleLowerCase("th").includes(term); }); }, [documents, query, status]);
  async function setArchived(document: AdminDocument, archived: boolean) { if (archived && !window.confirm(`เก็บเอกสาร ${document.title.th || document.slug} เป็นรายการถาวร?`)) return; setBusyId(document.id); setError(""); try { const response = await fetch(`/api/admin/documents/${document.id}/archive`, { body: JSON.stringify({ archived, reason: archived ? "Archived from Admin documents" : null }), headers: { "content-type": "application/json" }, method: "POST" }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error ?? "อัปเดตเอกสารไม่สำเร็จ"); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "อัปเดตเอกสารไม่สำเร็จ"); } finally { setBusyId(null); } }
  return <section className={styles.page}><header><div><span><FileText /></span><div><h1>เอกสาร</h1><p>เขียน ปักหมุด เผยแพร่ และจัดหมวดหมู่เอกสารสำหรับลูกค้า</p></div></div><Link href="/admin/documents/new"><FilePlus2 size={18} />สร้างเอกสาร</Link></header>
    <div className={styles.toolbar}><label><Search size={18} /><input aria-label="ค้นหาเอกสาร" onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาเอกสาร..." type="search" value={query} /></label><select aria-label="กรองสถานะเอกสาร" onChange={(event) => setStatus(event.target.value)} value={status}><option value="all">ทั้งหมด</option><option value="published">เผยแพร่</option><option value="draft">ฉบับร่าง</option><option value="archived">เก็บถาวร</option></select></div>
    {error ? <p className={styles.error} role="alert">{error}</p> : null}{documents.length === 0 ? <div className={styles.empty}><h2>ยังไม่มีเอกสาร</h2><p>สร้างเอกสารแรกเพื่อแสดงในศูนย์เอกสาร</p></div> : null}
    <div className={styles.table} role="table"><div className={styles.head} role="row"><span>ชื่อเอกสาร</span><span>หมวดหมู่</span><span>อัปเดตล่าสุด</span><span>สถานะ</span><span>จัดการ</span></div>{visible.map((document) => <div className={styles.row} key={document.id} role="row"><span><FileText size={17} /><b>{document.title.th || document.slug}</b><small>{document.slug}</small></span><span>{categoryLabels[document.category as keyof typeof categoryLabels] ?? document.category}</span><time>{new Intl.DateTimeFormat("th-TH", { dateStyle: "medium" }).format(new Date(document.updatedAt))}</time><em data-published={document.published && !document.archivedAt}>{document.archivedAt ? "เก็บถาวร" : document.published ? "เผยแพร่" : "ฉบับร่าง"}</em><span className={styles.actions}><Link aria-label={`แก้ไข ${document.title.th || document.slug}`} href={`/admin/documents/${document.id}`}><Pencil size={16} />แก้ไข</Link>{document.archivedAt ? <button aria-label={`กู้คืน ${document.title.th || document.slug}`} disabled={busyId === document.id} onClick={() => setArchived(document, false)} type="button"><RotateCcw size={16} /></button> : <button aria-label={`เก็บถาวร ${document.title.th || document.slug}`} disabled={busyId === document.id} onClick={() => setArchived(document, true)} type="button"><Archive size={16} /></button>}</span></div>)}</div>
  </section>;
}
